-- legacy_init.sql
-- Base de Datos: Db_OnPremise (Legacy)

-- 1. Limpieza
DROP TABLE IF EXISTS customers;

-- 2. Tabla Legacy (Ingles)
CREATE TABLE customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name VARCHAR(150) NOT NULL,
    email VARCHAR(100),
    total_balance DECIMAL(15, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Datos Historicos
INSERT INTO customers (business_name, email, total_balance) 
VALUES ('Tech Solutions Ltd.', 'contact@techsolutions.com', 50000.00);

INSERT INTO customers (business_name, email, total_balance) 
VALUES ('Global Imports Inc.', 'admin@globalimports.com', 12500.50);

INSERT INTO customers (business_name, email, total_balance) 
VALUES ('Consulting Group LLC', 'info@consultinggroup.com', 750.00);

-- 4. Ajuste de secuencia (Evitar colision de IDs 1, 2, 3)
ALTER TABLE customers ALTER COLUMN id RESTART WITH 4;