/*
Autor Henry Wong
GitHub hwongu

Descripción
Script para crear la base de datos Db_OnPremise, recrear la tabla customers e insertar datos de ejemplo para validación rápida
*/

-- Paso previo
-- Crea la base de datos si aún no existe
CREATE DATABASE "Db_OnPremise";

-- Nota
-- A partir de aquí ejecuta el resto del script conectado a la base de datos Db_OnPremise

-- 1 Limpieza
-- Elimina la tabla customers si existe para que el script pueda ejecutarse múltiples veces en pruebas
DROP TABLE IF EXISTS customers;

-- 2 Creación de la tabla customers
-- Tabla de clientes en esquema On Premise con nombres de columnas en inglés
CREATE TABLE customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador autogenerado
    business_name VARCHAR(150) NOT NULL,                     -- Nombre comercial
    email VARCHAR(100),                                      -- Correo de contacto opcional
    total_balance DECIMAL(15, 2) NOT NULL,                   -- Saldo total con 2 decimales
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP           -- Fecha de creación del registro
);

-- 3 Inserción de datos
-- Inserta registros de ejemplo para pruebas y validación
INSERT INTO customers (business_name, email, total_balance)
VALUES ('Tech Solutions Ltd.', 'contact@techsolutions.com', 50000.00);

INSERT INTO customers (business_name, email, total_balance)
VALUES ('Global Imports Inc.', 'admin@globalimports.com', 12500.50);

INSERT INTO customers (business_name, email, total_balance)
VALUES ('Consulting Group LLC', 'info@consultinggroup.com', 750.00);

-- 4 Verificación
-- Consulta para validar que los registros fueron insertados correctamente
SELECT * FROM customers;
